### ISSUE TITLE
(Sub) Theme not working

### ISSUE THREAD

**Issue by Vaggos** [dropdog/dropdog#24]
Our subtheme is not working properly when the profile is installed. In order to check if the problem is with the theme or the profile, I enabled the Bartik theme. Bartik is not working properly either. There is no header, no blocks (e.g. Footer → Powered by Drupal), no tabs (local tasks).

The enabled core modules of the profile installation are similar to a standard profile installation, but it seems that our profile is lacking vital functionality.

Are there pending additions for the Dropdog profile?

**Comment by theodorosploumis** [comment]
This issue was moved to dropdog/full-drupal#7
